defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: [vendor, favicon.xcf]

url: "http://benmadley.co.uk"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
